### ISSUE TITLE
As a user, I want to read the About page, so that I can understand the purpose of the project

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#13]
# User Story

*As a user, I want to read the About page, so that I can understand the purpose of the project*

## Acceptance Criteria

- [ ] About page is styled according to design document
- [ ] About page contains description of the game's goals as a portfolio project

## Tasks

- [ ] Style NavBar component
- [ ] Style basic CSS classes for `@apply` styles in TailwindCSS
- [ ] Describe the project and give credit to the authors
