### ISSUE TITLE
As a user, I want to read the user interface, so that I can understand what's happening in the game

### ISSUE THREAD

**Issue by SmoeJith** [trhopkins/super-bubble-stacker#16]
# User Story

*As a user, I want to see a user interface, so that I can understand what's happening in the game*

## Acceptance Criteria

- [ ] Button which begins play ("Start")
- [ ] Clearly delineated play area
- [ ] Scoreboard at the bottom of the play area
- [ ] Piece preview to the top of the right of the play area
- [ ] All GUI components are styled according to the design document

## Tasks

- [ ] Play area
  - [ ] Clearly bordered, rectangular, and centered in the page
  - [ ] Responsive, and accessible
  - [ ] Contains a canvas that is appropriately sized to display the game
  - [ ] Fits the look and feel outlined in the design document
- [ ] "Start" button
  - [ ] Exists as a modal that shadows the game elements
  - [ ] Disappears upon user clicking on it
  - [ ] Sends a signal / calls a function to initialize the game
  - [ ] Fits the look and feel outlined in the design document
- [ ] Scoreboard
  - [ ] Centered at the bottom of the play area
  - [ ] Holds the game's score in its state
  - [ ] Styled to be visually large and monospaced
  - [ ] Padded with zeroes
  - [ ] Fits the look and feel outlined in the design document
- [ ] Piece preview
  - [ ] Displays upcoming pieces in the order in which they appear
  - [ ] correctly shows the individual bubbles connecting to eachother
  - [ ] Stores the pieces in its state for the game to access
  - [ ] Aligned to the top of the right side of the play area
  - [ ] Fits the look and feel outlined in the design document

**Comment by trhopkins** [comment]
With the number of tasks here, we may want to break this story into several pieces and create an Epic (GitHub calls it a "Milestone") to track them in aggregate as several User Stories.

**Comment by trhopkins** [comment]
Here is a first draft of how I expect to lay everything out:

https://excalidraw.com/#json=eU0T3egsOuRN1hBGlfNXg,eY75qw_4_Y9kL847F2aigw


![Image](https://github.com/trhopkins/super-bubble-stacker/assets/80539439/11f33587-bcc1-473f-b3f7-eed192acc866)
