### ISSUE TITLE
As a player, I want to read the nuisance queue, so I can see how much nuisance is incoming

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#17]
# User Story

*As a player, I want to read the nuisance queue, so I can see how much nuisance is incoming*

## Acceptance Criteria

- [ ] Component displays incoming nuisance
- [ ] Component is styled and aligned properly
- [ ] Incoming nuisance is grouped and displayed with proper icons (greedy change-making algorithm)

## Tasks

- [ ] Create NuisanceQueue component
- [ ] Add 6x1 (192x32 pixels) canvas to component
- [ ] Style the component to be vertically aligned over the game board for both players
- [ ] Write [greedy change-making algorithm](https://en.wikipedia.org/wiki/Change-making_problem#Greedy_method) to calculate what icons should be displayed
  - [ ] Choose "largest" icons first
  - [ ] Display first 6 icons and hide the rest
  - [ ] Follow ["standard" nuisance queue icons](https://puyonexus.com/wiki/Nuisance_queue#Standard) (consider classic Puyo Puyo Tsu rules here?)
- [ ] Read incoming garbage values from game state (depends on  to implement this?)
- [ ] Update canvas visuals whenever remaining garbage value changes
- [ ] Unit test everything!
