### ISSUE TITLE
As a player, I want to read the next piece queue, so that I can plan my moves ahead

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#18]
# User Story

*As a player, I want to read the next piece queue, so that I can plan my moves ahead*

## Acceptance Criteria

- [ ] Component displays next two pieces in a queue
- [ ] Component is styled and aligned properly
- [ ] Incoming pieces are displayed according to Puyo Puyo standard or Puyo Puyo Tsu visuals

## Tasks

- [ ] Create NextPieceQueue component
- [ ] Add 2x4 (64x128 pixels) canvas to component (this ratio may change)
- [ ] Style the component to be horizontally aligned with the top of the game board for both players
- [ ] Implement Puyo Puyo Tsu's [next piece queue logic](https://puyonexus.com/wiki/Puyo_Puyo_Tsu/Upcoming_Pair_Randomizer) (a random queue is fine to start)
