### ISSUE TITLE
As a player, I want to view the game board, so that I can play the game

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#19]
# User Story

*As a player, I want to view the game board, so that I can play the game*

## Acceptance Criteria

- [ ] Component displays game board
- [ ] Component is styled and aligned properly
- [ ] Pieces can be drawn to the board (save game painting step for separate story)

## Tasks

- [ ] Create GameBoard component
- [ ] Add 6x12 (192x384 pixels) canvas to component
- [ ] Style the component to be vertically aligned below the nuisance queue for both players
