### ISSUE TITLE
As a player, I want to view the game's score, so I can determine how far into a game I am

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#20]
# Story Narrative

*As a player, I want to view the game's score, so I can determine how far into a game I am*

## Acceptance Criteria

- [ ] Component displays number of wins for each player
- [ ] Component is styled and aligned properly

## Tasks

- [ ] Create GameScore component
- [ ] Style the component to be centered at the top of the game view according to the design document
- [ ] Add a game score variable to the game's state management and track it when drawing the component
