### ISSUE TITLE
As a player, I want to see a character portrait, so I can see their reactions to sending/receiving attacks

### ISSUE THREAD

**Issue by trhopkins** [trhopkins/super-bubble-stacker#21]
# Story Narrative

*As a player, I want to see a character portrait, so I can see their reactions to sending/receiving attacks*

## Acceptance Criteria

- [ ] Component displays a character's portrait
- [ ] Component is styled and aligned properly
- [ ] Character portrait animates when an attack is sent or received

## Tasks

- [ ] Create CharacterPortrait component
- [ ] Add 3x3 (96x96 pixels) canvas to component (consider 2x2? Modeling Puyo Puyo Tsu here)
- [ ] Style the component to be aligned between each game board (below next piece queue)
- [ ] Add a sample character image
- [ ] Animate the character's face for sending/receiving damage
  - [ ] Display the size of the chain?
  - [ ] Happy/sad reactions
- [ ] Read game state to monitor when attacks are sent/received (requires the game logic to be actually implemented)
